# Generated by Django 5.0.14 on 2025-12-03 16:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertSubscription',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('user_hash', models.CharField(blank=True, default='', max_length=120)),
                ('name', models.CharField(blank=True, default='', max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('radius_meters', models.IntegerField(blank=True, null=True)),
                ('quiet_hours', models.CharField(blank=True, default='', max_length=40)),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('severity', models.CharField(max_length=20)),
                ('status', models.CharField(default='pending', max_length=40)),
                ('tags', models.JSONField(default=list)),
                ('location', models.JSONField(blank=True, null=True)),
                ('reporter', models.CharField(blank=True, default='', max_length=120)),
                ('reporter_first_name', models.CharField(blank=True, max_length=120, null=True)),
                ('reporter_last_name', models.CharField(blank=True, max_length=120, null=True)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('attachments', models.JSONField(default=list)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('admin_feedback', models.TextField(blank=True, default='')),
                ('zone_id', models.CharField(blank=True, max_length=20, null=True)),
                ('upvotes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(default='user', max_length=32)),
                ('name_given', models.CharField(max_length=100)),
                ('name_family', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('polygon_geojson', models.TextField()),
                ('version', models.IntegerField(default=1)),
                ('published_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='MailchimpEvent',
            fields=[
                ('id', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('mode', models.CharField(max_length=40)),
                ('type', models.CharField(max_length=60)),
                ('subject', models.CharField(max_length=200)),
                ('html', models.TextField()),
                ('recipients', models.JSONField(default=list)),
                ('reviewer', models.CharField(blank=True, default='', max_length=120)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.report')),
            ],
        ),
        migrations.CreateModel(
            name='FollowUpRequest',
            fields=[
                ('id', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('reporter_id', models.CharField(blank=True, default='', max_length=120)),
                ('reporter', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(default='pending', max_length=40)),
                ('feedback', models.TextField(blank=True, default='')),
                ('requested_at', models.DateTimeField()),
                ('reviewer', models.CharField(blank=True, default='', max_length=120)),
                ('review_link', models.CharField(blank=True, default='', max_length=200)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.report')),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.user'),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.report')),
            ],
        ),
    ]
