# Generated by Django 5.0.14 on 2025-12-04 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_replace_user_fk_with_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alertsubscription',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='alertsubscription',
            name='name',
        ),
        migrations.RemoveField(
            model_name='alertsubscription',
            name='quiet_hours',
        ),
        migrations.RemoveField(
            model_name='alertsubscription',
            name='radius_meters',
        ),
        migrations.RemoveField(
            model_name='alertsubscription',
            name='user_hash',
        ),
        migrations.AddField(
            model_name='alertsubscription',
            name='location',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alertsubscription',
            name='reporter',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
