export const incidentTypes = [
  { value: "theft", label: "Theft / Stealing" },
  { value: "vandalism", label: "Vandalism / Property Damage" },
  { value: "safety_hazard", label: "Safety Hazard" },
  { value: "fire", label: "Fire / Smoke" },
  { value: "accident", label: "Traffic Accident" },
  { value: "medical", label: "Medical Emergency" },
  { value: "suspicious", label: "Suspicious Activity" },
  { value: "harassment", label: "Harassment / Assault" },
  { value: "lost_found", label: "Lost or Found Item" },
  { value: "noise", label: "Noise Complaint" },
  { value: "power_outage", label: "Power Outage" },
  { value: "road_block", label: "Road Block / Obstruction" },
  { value: "weather", label: "Weather Hazard (Flood, Snow, etc.)" },
  { value: "animal", label: "Animal Incident" },
  { value: "pollution", label: "Pollution / Trash Issue" },
  { value: "graffiti", label: "Graffiti" },
  { value: "cybercrime", label: "Cybercrime / Scam" },
  { value: "missing_person", label: "Missing Person" },
  { value: "water_leak", label: "Water Leak / Pipe Burst" },
  { value: "gas_leak", label: "Gas Leak / Odor" },
  { value: "public_disturbance", label: "Public Disturbance" },
  { value: "other", label: "Other" },
];
